#
# This source file is part of the FitSync open source project
#
# SPDX-FileCopyrightText: 2022 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Build and Test

on:
  workflow_call:

jobs:
  reuse_action:
    name: REUSE Compliance Check
    uses: StanfordBDHG/.github/.github/workflows/reuse.yml@v2
  swiftlint:
    name: SwiftLint
    uses: StanfordBDHG/.github/.github/workflows/swiftlint.yml@v2
  packageios:
    name: Build and Test Swift Package iOS
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      scheme: FitSync
      resultBundle: FitSync-iOS.xcresult
      artifactname: FitSync-iOS.xcresult
  packagewatchos:
    name: Build and Test Swift Package watchOS
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      scheme: FitSync
      destination: 'platform=watchOS Simulator,name=Apple Watch Series 9 (45mm)'
      resultBundle: FitSync-watchOS.xcresult
      artifactname: FitSync-watchOS.xcresult
  packagevisionos:
    name: Build and Test Swift Package visionOS
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      scheme: FitSync
      destination: 'platform=visionOS Simulator,name=Apple Vision Pro'
      resultBundle: FitSync-visionOS.xcresult
      artifactname: FitSync-visionOS.xcresult
  packagetvos:
    name: Build and Test Swift Package tvOS
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      scheme: FitSync
      resultBundle: FitSync-tvOS.xcresult
      destination: 'platform=tvOS Simulator,name=Apple TV 4K (3rd generation)'
      artifactname: FitSync-tvOS.xcresult
  packagemacos:
    name: Build and Test Swift Package macOS
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      scheme: FitSync
      resultBundle: FitSync-macOS.xcresult
      destination: 'platform=macOS,arch=arm64'
      artifactname: FitSync-macOS.xcresult
  ios:
    name: Build and Test iOS
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      path: 'Tests/UITests'
      scheme: TestApp
      resultBundle: TestApp-iOS.xcresult
      artifactname: TestApp-iOS.xcresult
  ipados:
    name: Build and Test iPadOS
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      path: 'Tests/UITests'
      scheme: TestApp
      destination: 'platform=iOS Simulator,name=iPad Air (5th generation)'
      resultBundle: TestApp-iPadOS.xcresult
      artifactname: TestApp-iPadOS.xcresult
  watchos:
    name: Build and Test watchOS
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      runsonlabels: '["macOS", "self-hosted"]'
      path: 'Tests/UITests'
      scheme: TestAppWatchApp
      destination: 'platform=watchOS Simulator,name=Apple Watch Series 9 (45mm)'
      resultBundle: TestApp-watchOS.xcresult
      artifactname: TestApp-watchOS.xcresult
  visionos:
    name: Build and Test visionOS
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      runsonlabels: '["macOS", "self-hosted"]'
      path: 'Tests/UITests'
      scheme: TestApp
      destination: 'platform=visionOS Simulator,name=Apple Vision Pro'
      resultBundle: TestApp-visionOS.xcresult
      artifactname: TestApp-visionOS.xcresult
  tvos:
    name: Build and Test tvOS
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      path: 'Tests/UITests'
      scheme: TestApp
      destination: 'platform=tvOS Simulator,name=Apple TV 4K (3rd generation)'
      resultBundle: TestApp-tvOS.xcresult
      artifactname: TestApp-tvOS.xcresult
  codeql:
    name: CodeQL
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      codeql: true
      test: false
      scheme: FitSync
    permissions:
      security-events: write
      actions: read
  uploadcoveragereport:
    name: Upload Coverage Report
    needs: [packageios, packagewatchos, packagevisionos, packagetvos, packagemacos, ios, ipados, watchos, visionos, tvos]
    uses: StanfordBDHG/.github/.github/workflows/create-and-upload-coverage-report.yml@v2
    with:
      coveragereports: FitSync-iOS.xcresult FitSync-watchOS.xcresult FitSync-visionOS.xcresult FitSync-tvOS.xcresult FitSync-macOS.xcresult TestApp-iOS.xcresult TestApp-iPadOS.xcresult TestApp-watchOS.xcresult TestApp-visionOS.xcresult TestApp-tvOS.xcresult
    secrets:
      token: ${{ secrets.CODECOV_TOKEN }}
